export default [
    {
        "id": "1",
        "img": "../images/rec1594.png",
        "header": "How to do home repair",
        "contents": "Some wiring problems are just inconveniences, but others can pose serious fire or electrocution hazards. It’s important to diagnose and resolve a wiring issue as soon as you can. Simple wiring faults on electrical appliances can be diagnosed and solved using DIY manuals, which often contain a maintenance and repairs section that gives detailed step-by-step instructions for all home wiring repair and maintenance jobs.    Remember, if in doubt, call in a qualified electrician. Working with electricity can be hazardous, especially when you’re not sure what you’re doing!Electrical fittings are subject to more wear and tear than most household fixtures and fittings. It’s especially important not to ignore these problems since you’re dealing with live circuits that are especially hazardous. As always, safety is crucial when working with electrical or wiring faults. When tackling wiring issues remember to:Switch off the power at the mains supply and if working on an appliance unplug it Use the right tools for the job Remove the relevant circuit fuse Watch out for any exposed wiring Make sure there aren’t any liquids in the area you’re working on  Never fit a fuse that’s rated too highly for the circuit to protect Double check your work (particularly connections) before you turn the electricity back on"
    },
    {
        "id": "2",
        "img": "../images/rec1592.png",
        "header": "Power safety tips at home",
        "contents": "Some wiring problems are just inconveniences, but others can pose serious fire or electrocution hazards. It’s important to diagnose and resolve a wiring issue as soon as you can. Simple wiring faults on electrical appliances can be diagnosed and solved using DIY manuals, which often contain a maintenance and repairs section that gives detailed step-by-step instructions for all home wiring repair and maintenance jobs.    Remember, if in doubt, call in a qualified electrician. Working with electricity can be hazardous, especially when you’re not sure what you’re doing!Electrical fittings are subject to more wear and tear than most household fixtures and fittings. It’s especially important not to ignore these problems since you’re dealing with live circuits that are especially hazardous. As always, safety is crucial when working with electrical or wiring faults. When tackling wiring issues remember to:Switch off the power at the mains supply and if working on an appliance unplug it Use the right tools for the job Remove the relevant circuit fuse Watch out for any exposed wiring Make sure there aren’t any liquids in the area you’re working on  Never fit a fuse that’s rated too highly for the circuit to protect Double check your work (particularly connections) before you turn the electricity back on"
    },
    {
        "id": "3",
        "img": "../images/rec1593.png",
        "header": "How to prevent power surge",
        "contents": "Some wiring problems are just inconveniences, but others can pose serious fire or electrocution hazards. It’s important to diagnose and resolve a wiring issue as soon as you can. Simple wiring faults on electrical appliances can be diagnosed and solved using DIY manuals, which often contain a maintenance and repairs section that gives detailed step-by-step instructions for all home wiring repair and maintenance jobs.    Remember, if in doubt, call in a qualified electrician. Working with electricity can be hazardous, especially when you’re not sure what you’re doing!Electrical fittings are subject to more wear and tear than most household fixtures and fittings. It’s especially important not to ignore these problems since you’re dealing with live circuits that are especially hazardous. As always, safety is crucial when working with electrical or wiring faults. When tackling wiring issues remember to:Switch off the power at the mains supply and if working on an appliance unplug it Use the right tools for the job Remove the relevant circuit fuse Watch out for any exposed wiring Make sure there aren’t any liquids in the area you’re working on  Never fit a fuse that’s rated too highly for the circuit to protect Double check your work (particularly connections) before you turn the electricity back on"
           },
    {
        "id": "4",
        "img": "../images/rec1594.png",
        "header": "How to do home repair",
        "contents": "Some wiring problems are just inconveniences, but others can pose serious fire or electrocution hazards. It’s important to diagnose and resolve a wiring issue as soon as you can. Simple wiring faults on electrical appliances can be diagnosed and solved using DIY manuals, which often contain a maintenance and repairs section that gives detailed step-by-step instructions for all home wiring repair and maintenance jobs.    Remember, if in doubt, call in a qualified electrician. Working with electricity can be hazardous, especially when you’re not sure what you’re doing!Electrical fittings are subject to more wear and tear than most household fixtures and fittings. It’s especially important not to ignore these problems since you’re dealing with live circuits that are especially hazardous. As always, safety is crucial when working with electrical or wiring faults. When tackling wiring issues remember to:Switch off the power at the mains supply and if working on an appliance unplug it Use the right tools for the job Remove the relevant circuit fuse Watch out for any exposed wiring Make sure there aren’t any liquids in the area you’re working on  Never fit a fuse that’s rated too highly for the circuit to protect Double check your work (particularly connections) before you turn the electricity back on"
    },
    {
        "id": "5",
        "img": "../images/rec1592.png",
        "header": "Power safety tips at home",
        "contents": "Some wiring problems are just inconveniences, but others can pose serious fire or electrocution hazards. It’s important to diagnose and resolve a wiring issue as soon as you can. Simple wiring faults on electrical appliances can be diagnosed and solved using DIY manuals, which often contain a maintenance and repairs section that gives detailed step-by-step instructions for all home wiring repair and maintenance jobs.    Remember, if in doubt, call in a qualified electrician. Working with electricity can be hazardous, especially when you’re not sure what you’re doing!Electrical fittings are subject to more wear and tear than most household fixtures and fittings. It’s especially important not to ignore these problems since you’re dealing with live circuits that are especially hazardous. As always, safety is crucial when working with electrical or wiring faults. When tackling wiring issues remember to:Switch off the power at the mains supply and if working on an appliance unplug it Use the right tools for the job Remove the relevant circuit fuse Watch out for any exposed wiring Make sure there aren’t any liquids in the area you’re working on  Never fit a fuse that’s rated too highly for the circuit to protect Double check your work (particularly connections) before you turn the electricity back on"
    },
    {
        "id": "6",
        "img": "../images/rec1593.png",
        "header": "How to prevent power surge",
        "contents": "Some wiring problems are just inconveniences, but others can pose serious fire or electrocution hazards. It’s important to diagnose and resolve a wiring issue as soon as you can. Simple wiring faults on electrical appliances can be diagnosed and solved using DIY manuals, which often contain a maintenance and repairs section that gives detailed step-by-step instructions for all home wiring repair and maintenance jobs.    Remember, if in doubt, call in a qualified electrician. Working with electricity can be hazardous, especially when you’re not sure what you’re doing!Electrical fittings are subject to more wear and tear than most household fixtures and fittings. It’s especially important not to ignore these problems since you’re dealing with live circuits that are especially hazardous. As always, safety is crucial when working with electrical or wiring faults. When tackling wiring issues remember to:Switch off the power at the mains supply and if working on an appliance unplug it Use the right tools for the job Remove the relevant circuit fuse Watch out for any exposed wiring Make sure there aren’t any liquids in the area you’re working on  Never fit a fuse that’s rated too highly for the circuit to protect Double check your work (particularly connections) before you turn the electricity back on"
    }
]